name: quran
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  color: any
  fluttertoast: 3.0.4
  share: ^0.6.1+1
  url_launcher: 5.0.2
  flutter_share_me: 0.1.2
  flutter_launcher_icons: ^0.7.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  image_path: "assets/images/qlauncher.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/quran.png
    - assets/images/hadith.png
    - assets/images/makka.png
    - assets/images/madina.png
    - assets/images/bgImg.png
    - assets/images/qlauncher.png
    - assets/sura_list.json
    - assets/quran/1.json
    - assets/quran/2.json
    - assets/quran/3.json
    - assets/quran/4.json
    - assets/quran/5.json
    - assets/quran/6.json
    - assets/quran/7.json
    - assets/quran/8.json
    - assets/quran/9.json
    - assets/quran/10.json
    - assets/quran/11.json
    - assets/quran/12.json
    - assets/quran/13.json
    - assets/quran/14.json
    - assets/quran/15.json
    - assets/quran/16.json
    - assets/quran/17.json
    - assets/quran/18.json
    - assets/quran/19.json
    - assets/quran/20.json
    - assets/quran/21.json
    - assets/quran/22.json
    - assets/quran/23.json
    - assets/quran/24.json
    - assets/quran/25.json
    - assets/quran/26.json
    - assets/quran/27.json
    - assets/quran/28.json
    - assets/quran/29.json
    - assets/quran/30.json
    - assets/quran/31.json
    - assets/quran/32.json
    - assets/quran/33.json
    - assets/quran/34.json
    - assets/quran/35.json
    - assets/quran/36.json
    - assets/quran/37.json
    - assets/quran/38.json
    - assets/quran/39.json
    - assets/quran/40.json
    - assets/quran/41.json
    - assets/quran/42.json
    - assets/quran/43.json
    - assets/quran/44.json
    - assets/quran/45.json
    - assets/quran/46.json
    - assets/quran/47.json
    - assets/quran/48.json
    - assets/quran/49.json
    - assets/quran/50.json
    - assets/quran/51.json
    - assets/quran/52.json
    - assets/quran/53.json
    - assets/quran/54.json
    - assets/quran/55.json
    - assets/quran/56.json
    - assets/quran/57.json
    - assets/quran/58.json
    - assets/quran/59.json
    - assets/quran/60.json
    - assets/quran/61.json
    - assets/quran/62.json
    - assets/quran/63.json
    - assets/quran/64.json
    - assets/quran/65.json
    - assets/quran/66.json
    - assets/quran/67.json
    - assets/quran/68.json
    - assets/quran/69.json
    - assets/quran/70.json
    - assets/quran/71.json
    - assets/quran/72.json
    - assets/quran/73.json
    - assets/quran/74.json
    - assets/quran/75.json
    - assets/quran/76.json
    - assets/quran/77.json
    - assets/quran/78.json
    - assets/quran/79.json
    - assets/quran/80.json
    - assets/quran/81.json
    - assets/quran/82.json
    - assets/quran/83.json
    - assets/quran/84.json
    - assets/quran/85.json
    - assets/quran/86.json
    - assets/quran/87.json
    - assets/quran/88.json
    - assets/quran/89.json
    - assets/quran/90.json
    - assets/quran/91.json
    - assets/quran/92.json
    - assets/quran/93.json
    - assets/quran/94.json
    - assets/quran/95.json
    - assets/quran/96.json
    - assets/quran/97.json
    - assets/quran/98.json
    - assets/quran/99.json
    - assets/quran/100.json
    - assets/quran/101.json
    - assets/quran/102.json
    - assets/quran/103.json
    - assets/quran/104.json
    - assets/quran/105.json
    - assets/quran/106.json
    - assets/quran/107.json
    - assets/quran/108.json
    - assets/quran/109.json
    - assets/quran/110.json
    - assets/quran/111.json
    - assets/quran/112.json
    - assets/quran/113.json
    - assets/quran/114.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Scheherazade
       fonts:
         - asset: assets/fonts/qur_std.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
